version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
#      - ./sql/mysql_dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    restart: always
    container_name: mysql-bgm
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build:
      context: .
#   image: wordpress:4.4
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    container_name: wp-bgm
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

