version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
#      - ./sql/mysql_dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    restart: always
    container_name: mysql-nuk
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      TZ: Asia/Tokyo

  wordpress:
    depends_on:
      - db
    build:
      context: .
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    container_name: wp-nuk
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      TZ: Asia/Tokyo


;; 修正時刻: Mon Jan 31 13:22:38 2022
